apiVersion: v1
kind: Pod
metadata:
  name: task-pv-pod
  namespace: jenkins
spec:
  volumes:
    - name: jenkins-home-restore
      persistentVolumeClaim:
        claimName: jenkins-home-restore
  containers:
    - name: task-pv-container
      image: centos
      command: ["/bin/sh"]
      args: ["-c", "sleep 100000"]
      volumeMounts:
        - mountPath: "/data"
          name: jenkins-home-restore