apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-home-restore-2
  namespace: jenkins
spec:
  storageClassName: ebs-sc
  dataSource:
    name: jenkins-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi